### ISSUE TITLE
panic on get

### ISSUE THREAD

**Issue by tcurdt** [ducaale/ht#13]
Ups?!

```
 % ht -V
ht 0.3.5

% RUST_BACKTRACE=full ht get https://google.de
HTTP/2.0 400 Bad Request
content-length: 1555
content-type: text/html; charset=UTF-8
date: Sat, 06 Feb 2021 01:51:40 GMT
referrer-policy: no-referrer

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Proto(PROTOCOL_ERROR) }) }', src/printer.rs:208:79
stack backtrace:
   0:        0x10cc13104 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha0848bb2602b5d05
   1:        0x10cc31b20 - core::fmt::write::h9f3ccac2ef682b93
   2:        0x10cc0cc86 - std::io::Write::write_fmt::h0a47673aab280496
   3:        0x10cc14ee9 - std::panicking::default_hook::{{closure}}::h850c6aaf5e80c2f5
   4:        0x10cc14bad - std::panicking::default_hook::h037801299da6e1c6
   5:        0x10cc1556b - std::panicking::rust_panic_with_hook::h76436d4cf7a368ac
   6:        0x10cc15095 - std::panicking::begin_panic_handler::{{closure}}::h516c76d70abf04f6
   7:        0x10cc13578 - std::sys_common::backtrace::__rust_end_short_backtrace::h653290b4f930faed
   8:        0x10cc14ffa - _rust_begin_unwind
   9:        0x10cc44d5f - core::panicking::panic_fmt::hde9134dd19c9a74f
  10:        0x10cc44c65 - core::result::unwrap_failed::hcef4aa8b48b8f381
  11:        0x10c85639e - ht::main::{{closure}}::he3ac16d2a9991dec
  12:        0x10c8410cf - std::thread::local::LocalKey<T>::with::he4e6385d82693aed
  13:        0x10c868df7 - tokio::runtime::enter::Enter::block_on::ha21fbfb709a85010
  14:        0x10c87d6bb - tokio::runtime::thread_pool::ThreadPool::block_on::h85096403de5f2e48
  15:        0x10c834583 - tokio::runtime::Runtime::block_on::hcb3032661041b561
  16:        0x10c869b94 - ht::main::h1c0bf400bc026e2c
  17:        0x10c878dea - std::sys_common::backtrace::__rust_begin_short_backtrace::h23c3e2aace5f6064
  18:        0x10c879371 - std::rt::lang_start::{{closure}}::h61625dd6a2f250f3
  19:        0x10cc158e4 - std::rt::lang_start_internal::h36ccce6e8a047133
  20:        0x10c869c79 - _main
```

**Comment by iruoy** [comment]
Happens on 0.4.0 as well

<details>
  <summary>version</summary>
  
  ```
  % ht -V
  ht 0.4.0
  ```
</details>

<details>
  <summary>error</summary>
  
  ```
  % RUST_BACKTRACE=full ht get https://google.com
  HTTP/2.0 400 Bad Request
  content-length: 1555
  content-type: text/html; charset=UTF-8
  date: Sat, 06 Feb 2021 02:20:30 GMT
  referrer-policy: no-referrer
  
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Proto(PROTOCOL_ERROR) }) }', /home/youri/.cargo/registry/src/github.com-1ecc6299db9ec823/ht-0.4.0/src/printer.rs:183:79
  stack backtrace:
     0:     0x555fe7c41010 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
     1:     0x555fe7c41010 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x555fe7c41010 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x555fe7c41010 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x555fe7c62dcc - core::fmt::write::h77b4746b0dea1dd3
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
     5:     0x555fe7c3a902 - std::io::Write::write_fmt::heb7e50902e98831c
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
     6:     0x555fe7c435c5 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x555fe7c435c5 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x555fe7c435c5 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
     9:     0x555fe7c43268 - std::panicking::default_hook::hb52d73f0da9a4bb8
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
    10:     0x555fe7c43d61 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
    11:     0x555fe7c438a7 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
    12:     0x555fe7c414cc - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x555fe7c43809 - rust_begin_unwind
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
    14:     0x555fe7c60d31 - core::panicking::panic_fmt::ha0bb065d9a260792
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
    15:     0x555fe7c60b53 - core::option::expect_none_failed::h7e1dd0a94971eb61
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
    16:     0x555fe7894231 - ht::main::{{closure}}::hd7be580a5542f740
    17:     0x555fe787d98c - std::thread::local::LocalKey<T>::with::ha396fb4a19d6734a
    18:     0x555fe78ade2d - tokio::park::thread::CachedParkThread::block_on::h7937ad2a99e90987
    19:     0x555fe78ae074 - tokio::runtime::thread_pool::ThreadPool::block_on::h93301ffc9e0994a0
    20:     0x555fe786fde0 - tokio::runtime::Runtime::block_on::he9dd9913bb7ad25a
    21:     0x555fe78a7da8 - ht::main::h221352a1e6d78f6e
    22:     0x555fe78b7e33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8ec060ea6a0acd07
    23:     0x555fe78c7bcd - std::rt::lang_start::{{closure}}::ha87101063ce3be99
    24:     0x555fe7c44187 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
    25:     0x555fe7c44187 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
    26:     0x555fe7c44187 - std::panicking::try::hbeeb95b4e1f0a876
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
    27:     0x555fe7c44187 - std::panic::catch_unwind::h59c48ccb40a0bf20
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
    28:     0x555fe7c44187 - std::rt::lang_start_internal::ha53ab63f88fee728
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
    29:     0x555fe78a7e72 - main
    30:     0x7f30e2c96152 - __libc_start_main
    31:     0x555fe78651fe - _start
    32:                0x0 - <unknown>
  ```
</details>

**Comment by iruoy** [comment]
Looks like it's an easy fix. See #12.

**Comment by Till--H** [comment]
I think this is related to https://github.com/seanmonstar/reqwest/issues/893#issuecomment-620625652, i.e., the `host` being explicitly set in conjunction with a HTTP 2 request being made.
