### ISSUE TITLE
Broken pipe panic when piping output

### ISSUE THREAD

**Issue by drien** [ducaale/ht#14]
Thanks for this, it's dramatically faster than the original when pretty printing big JSON responses!

When piping to `head` or `less` I'm seeing a broken pipe-related panic when the pager exits. Seems likely to be related to this? https://github.com/rust-lang/rust/issues/46016

Reproducing it requires a response of sufficient length:

```
22:02:25 ~ > RUST_BACKTRACE=1 ht get 'http://httpbin.org/stream/150' | head
{"url": "http://httpbin.org/stream/150", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-601e06c4-02a347b5507c64fe408cf5b6", "Accept-Encoding": "gzip, deflate", "Accept": "*/*"}, "origin": "104.162.100.223", "id": 0}

{"url": "http://httpbin.org/stream/150", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-601e06c4-02a347b5507c64fe408cf5b6", "Accept-Encoding": "gzip, deflate", "Accept": "*/*"}, "origin": "104.162.100.223", "id": 1}

{"url": "http://httpbin.org/stream/150", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-601e06c4-02a347b5507c64fe408cf5b6", "Accept-Encoding": "gzip, deflate", "Accept": "*/*"}, "origin": "104.162.100.223", "id": 2}

{"url": "http://httpbin.org/stream/150", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-601e06c4-02a347b5507c64fe408cf5b6", "Accept-Encoding": "gzip, deflate", "Accept": "*/*"}, "origin": "104.162.100.223", "id": 3}

{"url": "http://httpbin.org/stream/150", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-601e06c4-02a347b5507c64fe408cf5b6", "Accept-Encoding": "gzip, deflate", "Accept": "*/*"}, "origin": "104.162.100.223", "id": 4}

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:895:9
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:429
   2: std::io::stdio::print_to
             at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/io/stdio.rs:895
   3: std::io::stdio::_print
             at /build/rustc-71Ymwo/rustc-1.47.0+dfsg1+llvm/library/std/src/io/stdio.rs:907
   4: ht::buffer::Buffer::write
   5: ht::main::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::Runtime::block_on
  10: ht::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Installed from cargo, rustc 1.47.0
Ubuntu 20.10 / Linux 5.8.0-41-generic

**Comment by blyxxyz** [comment]
HTTPie, curl and wget also give an error message when piped into `head`, so it's probably ok to crash.

(But maybe it should be a controlled crash with an error message, not a panic.)
